### ISSUE TITLE
Power Decibel 

### ISSUE THREAD

**Issue by Toku11** [seth814/Audio-Classification#10]
Why are you using power_melgram as 1.0 instead of 2.0 which is the usual parameter for Mel Spectrogram. And What do you think about Delta? Kapre has no module to add Deltas but is it a good idea to stack deltas?

**Comment by seth814** [comment]
That is a good point. For some reason when I put this together I just used the defaults and went with it. It should be set to 2.0. I'll make that change soon.

I don't really have an opinion on deltas because I haven't messed around with them, but concatenating the delta mel early in the model probably can't hurt. You'd have to try it yourself.

**Comment by Toku11** [comment]
Perfect! I will add Deltas Layer to Kapre to check it out, thanks. Closing Issue.
